language: python
branches:
only:
  - master
python:
  - "2.7"
  - "3.4"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
# Install packages
install:
  - conda install -y gdal
  - conda install -y futures
  - conda install -y -c https://conda.binstar.org/ocefpaf pyproj
  - pip install svgwrite
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=scalebar
