language: python
branches:
only:
  - master
python:
  - "2.7"

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env
  - which python
# Install packages
install:
  - conda install -y nose gdal futures
  - conda install -y -c https://conda.binstar.org/ocefpaf pyproj
  - pip install svgwrite
  - pip install sphinx sphinxcontrib-napoleon
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=scalebar
after_success:
  - coveralls
